### ISSUE TITLE
ActiveSupport 4.1.6 gives "uninitialized constant ActiveSupport::Autoload"

### ISSUE THREAD

**Issue by mfrederickson** [gokuu/jasper-command-line#5]
https://github.com/gokuu/jasper-command-line/blob/master/lib/jasper-command-line.rb#L5

I had to include `require 'active_support'` above this line to make it work-- otherwise I was getting errors like the following

```
active_support/number_helper.rb:3 uninitialized constant ActiveSupport::Autoload
...
mfrederickson@artemis2:~/projects/light-me-up$ jasper-command-line 
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric/conversions.rb:2:in `require'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric.rb:3:in `require'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:2:in `require'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:1:in `each'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/jasper-command-line-0.4.1/lib/jasper-command-line.rb:5:in `require'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/jasper-command-line-0.4.1/lib/jasper-command-line.rb:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/jasper-command-line-0.4.1/bin/jasper-command-line:3:in `require'
    from /usr/local/rvm/gems/ruby-2.1.2/gems/jasper-command-line-0.4.1/bin/jasper-command-line:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.2/bin/jasper-command-line:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.2/bin/jasper-command-line:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by danieldenis01** [comment]
Add also: require 'active_support/core_ext'. It worked for me.
